#!/bin/sh

# Usage: ./runall <command to run your program>
# For instance, if your program can be run with 'python code/assemble.py',
# you could run ./runall python code/assemble.py

for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
do
    COUNT=$(wc -c < output${i}.txt)
    echo "output${i}.txt : $COUNT"
done
