#!/bin/sh

# Usage: ./runall <command to run your program>
# For instance, if your program can be run with 'python assemble.py',
# you could run ./runall python assemble.py

for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
do
    echo Running on reads${i}.txt...
    START=$(date +%s)
    $* < reads${i}.txt > output${i}.txt
    END=$(date +%s)
    echo Comparing your output${i}.txt to the correct answer....
    cmp output${i}.txt answer/answer${i}.txt && echo output${i}.txt looks good
    echo time elapsed : $(($END - $START))s
done
